/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AnchorToPagesButton: typeof import('./src/components/AnchorToPagesButton/index.vue')['default']
    App: typeof import('./src/App.vue')['default']
    CommunityPhotos: typeof import('./src/views/CommunityPhotos.vue')['default']
    Dashboard: typeof import('./src/layout/Dashboard.vue')['default']
    Default: typeof import('./src/layout/Default.vue')['default']
    EmailConfirmation: typeof import('./src/views/EmailConfirmation.vue')['default']
    EmbeddedPlaylist: typeof import('./src/components/Playlist/EmbeddedPlaylist/index.vue')['default']
    FancyBox: typeof import('./src/components/CommunityPhotos/FancyBox/index.vue')['default']
    ForgotPassword: typeof import('./src/views/ForgotPassword.vue')['default']
    ForgotPasswordForm: typeof import('./src/components/ForgotPasswordForm/index.vue')['default']
    Gift: typeof import('./src/views/Gift.vue')['default']
    GuestAccordion: typeof import('./src/components/GuestAccordion/index.vue')['default']
    GuestForm: typeof import('./src/components/GuestForm/index.vue')['default']
    Home: typeof import('./src/views/Home.vue')['default']
    HomeLayout: typeof import('./src/layout/HomeLayout.vue')['default']
    Invitation: typeof import('./src/views/Invitation.vue')['default']
    InvitationForm: typeof import('./src/components/InvitationForm/index.vue')['default']
    Login: typeof import('./src/views/Login.vue')['default']
    LoginForm: typeof import('./src/components/LoginForm/index.vue')['default']
    Menu: typeof import('./src/views/Menu.vue')['default']
    Navigation: typeof import('./src/components/Navigation/index.vue')['default']
    Playlist: typeof import('./src/views/Playlist.vue')['default']
    RecoverPassword: typeof import('./src/views/RecoverPassword.vue')['default']
    RecoverPasswordForm: typeof import('./src/components/RecoverPasswordForm/index.vue')['default']
    Register: typeof import('./src/views/Register.vue')['default']
    RegisterForm: typeof import('./src/components/RegisterForm/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchForm: typeof import('./src/components/Playlist/SearchForm/index.vue')['default']
    Timeline: typeof import('./src/components/CommunityPhotos/Timeline/index.vue')['default']
    Timer: typeof import('./src/components/Timer/index.vue')['default']
    Track: typeof import('./src/components/Playlist/Track/index.vue')['default']
  }
}
